% Author     :   F. Moissenet
%                Biomechanics Laboratory (B-LAB)
%                Geneva University Hospital and University of Geneva
%                https://www.unige.ch/medecine/chiru/fr/b-lab-tests-robotises-avances-de-dispositifs-chirurgicaux/
% License    :   Creative Commons Attribution-NonCommercial 4.0 International License 
%                https://creativecommons.org/licenses/by-nc/4.0/legalcode
% Source code:   To be defined
% Reference  :   To be defined
% Date       :   July 2023
% -------------------------------------------------------------------------
% Description:   Plot dynamic bone pose
% -------------------------------------------------------------------------
% Dependencies : - patch_array3
% -------------------------------------------------------------------------
% This work is licensed under the Creative Commons Attribution - 
% NonCommercial 4.0 International License. To view a copy of this license, 
% visit http://creativecommons.org/licenses/by-nc/4.0/ or send a letter to 
% Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
% -------------------------------------------------------------------------

function [] = PlotDynamic(Bone,Trial,type,itrial,plotview,showVertices)

figure(1);
n = length(1:size(Bone(1).Trial(itrial).SCS.T,3));

for t = 1:n
    
    quiver3(0,0,0,1,0,0,0.1,'red');
    hold on; axis equal; view(0,90);
    quiver3(0,0,0,0,1,0,0.1,'green');
    quiver3(0,0,0,0,0,1,0.1,'blue');
    
    % ---------------------------------------------------------------------
    % HUMERUS
    % ---------------------------------------------------------------------
    if showVertices == 1
        vertices = [Bone(1).(type)(itrial).Meshl.vertices_t(1,:,t); ...
                    -Bone(1).(type)(itrial).Meshl.vertices_t(3,:,t); ...
                    Bone(1).(type)(itrial).Meshl.vertices_t(2,:,t)];
        patch_array3(Bone(1).(type)(itrial).Meshl.faces,...
                     vertices,...
                     [0.7 0.7 0.7],'none','gouraud',1);
        clear vertices;
    end
    xlabel('x'); ylabel('y'); zlabel('z');
    for imarker = 1:4
        plot3(Bone(1).(type)(itrial).Landmark(imarker).coordinates_t(1,1,t),...
              -Bone(1).(type)(itrial).Landmark(imarker).coordinates_t(3,1,t),...
              Bone(1).(type)(itrial).Landmark(imarker).coordinates_t(2,1,t),...
              'Marker','.','MarkerSize',15,'Color','red');
    end
    for ilandmark = 5:12
        plot3(Bone(1).(type)(itrial).Landmark(ilandmark).coordinates_t(1,1,t),...
              -Bone(1).(type)(itrial).Landmark(ilandmark).coordinates_t(3,1,t),...
              Bone(1).(type)(itrial).Landmark(ilandmark).coordinates_t(2,1,t),...
              'Marker','.','MarkerSize',15,'Color','green');
    end
    for ilandmark = 12+1:size(Bone(1).(type)(itrial).Landmark,2)
        plot3(Bone(1).(type)(itrial).Landmark(ilandmark).coordinates_t(1,1,t),...
              -Bone(1).(type)(itrial).Landmark(ilandmark).coordinates_t(3,1,t),...
              Bone(1).(type)(itrial).Landmark(ilandmark).coordinates_t(2,1,t),...
              'Marker','.','MarkerSize',15,'Color','blue');
    end
    [x,y,z] = sphere;
    surf(x*Bone(1).(type)(itrial).Object(1).radius+Bone(1).(type)(itrial).Object(1).centre_t(1,1,t), ...
         y*Bone(1).(type)(itrial).Object(1).radius-Bone(1).(type)(itrial).Object(1).centre_t(3,1,t), ...
         z*Bone(1).(type)(itrial).Object(1).radius+Bone(1).(type)(itrial).Object(1).centre_t(2,1,t),...
         'Facecolor','blue','FaceAlpha',0.3);
    quiver3(Bone(1).(type)(itrial).SCS.O_t(1,1,1),-Bone(1).(type)(itrial).SCS.O_t(3,1,1),Bone(1).(type)(itrial).SCS.O_t(2,1,t), ...
            Bone(1).(type)(itrial).SCS.X_t(1,1,1),-Bone(1).(type)(itrial).SCS.X_t(3,1,1),Bone(1).(type)(itrial).SCS.X_t(2,1,t),...
            0.1,'Color','red');
    quiver3(Bone(1).(type)(itrial).SCS.O_t(1,1,1),-Bone(1).(type)(itrial).SCS.O_t(3,1,1),Bone(1).(type)(itrial).SCS.O_t(2,1,t), ...
            Bone(1).(type)(itrial).SCS.Y_t(1,1,1),-Bone(1).(type)(itrial).SCS.Y_t(3,1,1),Bone(1).(type)(itrial).SCS.Y_t(2,1,t),...
            0.1,'Color','green');
    quiver3(Bone(1).(type)(itrial).SCS.O_t(1,1,1),-Bone(1).(type)(itrial).SCS.O_t(3,1,1),Bone(1).(type)(itrial).SCS.O_t(2,1,t), ...
            Bone(1).(type)(itrial).SCS.Z_t(1,1,1),-Bone(1).(type)(itrial).SCS.Z_t(3,1,1),Bone(1).(type)(itrial).SCS.Z_t(2,1,t),...
            0.1,'Color','blue'); 

    % ---------------------------------------------------------------------
    % SCAPULA
    % --------------------------------------------------------------------- 
    if showVertices == 1
        vertices = [Bone(2).(type)(itrial).Meshl.vertices_t(1,:,t); ...
                    -Bone(2).(type)(itrial).Meshl.vertices_t(3,:,t); ...
                    Bone(2).(type)(itrial).Meshl.vertices_t(2,:,t)];
        patch_array3(Bone(2).(type)(itrial).Meshl.faces,...
                     vertices,...
                     [0.7 0.7 0.7],'none','gouraud',1);
        clear vertices;
    end
    for imarker = 1:4
        plot3(Bone(2).(type)(itrial).Landmark(imarker).coordinates_t(1,1,t),...
              -Bone(2).(type)(itrial).Landmark(imarker).coordinates_t(3,1,t),...
              Bone(2).(type)(itrial).Landmark(imarker).coordinates_t(2,1,t),...
              'Marker','.','MarkerSize',15,'Color','red');
    end
    for ilandmark = 5:12
        plot3(Bone(2).(type)(itrial).Landmark(ilandmark).coordinates_t(1,1,t),...
              -Bone(2).(type)(itrial).Landmark(ilandmark).coordinates_t(3,1,t),...
              Bone(2).(type)(itrial).Landmark(ilandmark).coordinates_t(2,1,t),...
              'Marker','.','MarkerSize',15,'Color','green');
    end
    for ilandmark = 12+1:size(Bone(2).(type)(itrial).Landmark,2)
        plot3(Bone(2).(type)(itrial).Landmark(ilandmark).coordinates_t(1,1,t),...
              -Bone(2).(type)(itrial).Landmark(ilandmark).coordinates_t(3,1,t),...
              Bone(2).(type)(itrial).Landmark(ilandmark).coordinates_t(2,1,t),...
              'Marker','.','MarkerSize',15,'Color','blue');
    end
    quiver3(Bone(2).(type)(itrial).SCS.O_t(1,1,t),-Bone(2).(type)(itrial).SCS.O_t(3,1,t),Bone(2).(type)(itrial).SCS.O_t(2,1,t), ...
            Bone(2).(type)(itrial).SCS.X_t(1,1,t),-Bone(2).(type)(itrial).SCS.X_t(3,1,t),Bone(2).(type)(itrial).SCS.X_t(2,1,t),...
            0.1,'Color','red');
    quiver3(Bone(2).(type)(itrial).SCS.O_t(1,1,t),-Bone(2).(type)(itrial).SCS.O_t(3,1,t),Bone(2).(type)(itrial).SCS.O_t(2,1,t), ...
            Bone(2).(type)(itrial).SCS.Y_t(1,1,t),-Bone(2).(type)(itrial).SCS.Y_t(3,1,t),Bone(2).(type)(itrial).SCS.Y_t(2,1,t),...
            0.1,'Color','green');
    quiver3(Bone(2).(type)(itrial).SCS.O_t(1,1,t),-Bone(2).(type)(itrial).SCS.O_t(3,1,t),Bone(2).(type)(itrial).SCS.O_t(2,1,t), ...
            Bone(2).(type)(itrial).SCS.Z_t(1,1,t),-Bone(2).(type)(itrial).SCS.Z_t(3,1,t),Bone(2).(type)(itrial).SCS.Z_t(2,1,t),...
            0.1,'Color','blue'); 

    % ---------------------------------------------------------------------
    % CLAVICLE
    % ---------------------------------------------------------------------
    if showVertices == 1
        vertices = [Bone(3).(type)(itrial).Meshl.vertices_t(1,:,t); ...
                    -Bone(3).(type)(itrial).Meshl.vertices_t(3,:,t); ...
                    Bone(3).(type)(itrial).Meshl.vertices_t(2,:,t)];
        patch_array3(Bone(3).(type)(itrial).Meshl.faces,...
                     vertices,...
                     [0.7 0.7 0.7],'none','gouraud',1);
        clear vertices;
    end
    for imarker = 1:4
        plot3(Bone(3).(type)(itrial).Landmark(imarker).coordinates_t(1,1,t),...
              -Bone(3).(type)(itrial).Landmark(imarker).coordinates_t(3,1,t),...
              Bone(3).(type)(itrial).Landmark(imarker).coordinates_t(2,1,t),...
              'Marker','.','MarkerSize',15,'Color','red');
    end
    for ilandmark = 5:9
        plot3(Bone(3).(type)(itrial).Landmark(ilandmark).coordinates_t(1,1,t),...
              -Bone(3).(type)(itrial).Landmark(ilandmark).coordinates_t(3,1,t),...
              Bone(3).(type)(itrial).Landmark(ilandmark).coordinates_t(2,1,t),...
              'Marker','.','MarkerSize',15,'Color','green');
    end
    quiver3(Bone(3).(type)(itrial).SCS.O_t(1,1,t),-Bone(3).(type)(itrial).SCS.O_t(3,1,t),Bone(3).(type)(itrial).SCS.O_t(2,1,t), ...
            Bone(3).(type)(itrial).SCS.X_t(1,1,t),-Bone(3).(type)(itrial).SCS.X_t(3,1,t),Bone(3).(type)(itrial).SCS.X_t(2,1,t),...
            0.1,'Color','red');
    quiver3(Bone(3).(type)(itrial).SCS.O_t(1,1,t),-Bone(3).(type)(itrial).SCS.O_t(3,1,t),Bone(3).(type)(itrial).SCS.O_t(2,1,t), ...
            Bone(3).(type)(itrial).SCS.Y_t(1,1,t),-Bone(3).(type)(itrial).SCS.Y_t(3,1,t),Bone(3).(type)(itrial).SCS.Y_t(2,1,t),...
            0.1,'Color','green');
    quiver3(Bone(3).(type)(itrial).SCS.O_t(1,1,t),-Bone(3).(type)(itrial).SCS.O_t(3,1,t),Bone(3).(type)(itrial).SCS.O_t(2,1,t), ...
            Bone(3).(type)(itrial).SCS.Z_t(1,1,t),-Bone(3).(type)(itrial).SCS.Z_t(3,1,t),Bone(3).(type)(itrial).SCS.Z_t(2,1,t),...
            0.1,'Color','blue');

    % ---------------------------------------------------------------------
    % THORAX
    % ---------------------------------------------------------------------
    if showVertices == 1
        vertices = [Bone(4).(type)(itrial).Meshl.vertices_t(1,:,t); ...
                    -Bone(4).(type)(itrial).Meshl.vertices_t(3,:,t); ...
                    Bone(4).(type)(itrial).Meshl.vertices_t(2,:,t)];
        patch_array3(Bone(4).(type)(itrial).Meshl.faces,...
                     vertices,...
                     [0.7 0.7 0.7],'none','gouraud',0.1);
        clear vertices;
    end
    xlabel('x'); ylabel('y'); zlabel('z');
    for imarker = 1:4
        plot3(Bone(4).(type)(itrial).Landmark(imarker).coordinates_t(1,1,t),...
              -Bone(4).(type)(itrial).Landmark(imarker).coordinates_t(3,1,t),...
              Bone(4).(type)(itrial).Landmark(imarker).coordinates_t(2,1,t),...
              'Marker','.','MarkerSize',15,'Color','red');
    end
    for ilandmark = 5:14
        plot3(Bone(4).(type)(itrial).Landmark(ilandmark).coordinates_t(1,1,t),...
              -Bone(4).(type)(itrial).Landmark(ilandmark).coordinates_t(3,1,t),...
              Bone(4).(type)(itrial).Landmark(ilandmark).coordinates_t(2,1,t),...
              'Marker','.','MarkerSize',15,'Color','green');
    end
    quiver3(Bone(4).(type)(itrial).SCS.O_t(1,1,t),-Bone(4).(type)(itrial).SCS.O_t(3,1,t),Bone(4).(type)(itrial).SCS.O_t(2,1,t), ...
            Bone(4).(type)(itrial).SCS.X_t(1,1,t),-Bone(4).(type)(itrial).SCS.X_t(3,1,t),Bone(4).(type)(itrial).SCS.X_t(2,1,t),...
            0.1,'Color','red');
    quiver3(Bone(4).(type)(itrial).SCS.O_t(1,1,t),-Bone(4).(type)(itrial).SCS.O_t(3,1,t),Bone(4).(type)(itrial).SCS.O_t(2,1,t), ...
            Bone(4).(type)(itrial).SCS.Y_t(1,1,t),-Bone(4).(type)(itrial).SCS.Y_t(3,1,t),Bone(4).(type)(itrial).SCS.Y_t(2,1,t),...
            0.1,'Color','green');
    quiver3(Bone(4).(type)(itrial).SCS.O_t(1,1,t),-Bone(4).(type)(itrial).SCS.O_t(3,1,t),Bone(4).(type)(itrial).SCS.O_t(2,1,t), ...
            Bone(4).(type)(itrial).SCS.Z_t(1,1,t),-Bone(4).(type)(itrial).SCS.Z_t(3,1,t),Bone(4).(type)(itrial).SCS.Z_t(2,1,t),...
            0.1,'Color','blue');
        
    % ---------------------------------------------------------------------
    % SETTINGS
    % ---------------------------------------------------------------------
    axis off;
    if strcmp(plotview,'back')
        view(-90,0); % back
        xlim([-0.5 0.5]);
        ylim([-0.5 0.5]);
        zlim([-0.5 0.5]);
    elseif strcmp(plotview,'front')
        view(90,0); % front
        xlim([-0.5 0.5]);
        ylim([-0.5 0.5]);
        zlim([-0.5 0.5]);
    end
    lightangle(gca,0,45);
    set(gcf,'color','white');
    set(gcf,'position',[200,200,500,500])

    if t ~= Trial(itrial).n1
        pause(0.001);
        cla;
        hold off;
    end
    
end 