% Author     :   F. Moissenet
%                Biomechanics Laboratory (B-LAB)
%                Geneva University Hospital and University of Geneva
%                https://www.unige.ch/medecine/chiru/fr/b-lab-tests-robotises-avances-de-dispositifs-chirurgicaux/
% License    :   Creative Commons Attribution-NonCommercial 4.0 International License 
%                https://creativecommons.org/licenses/by-nc/4.0/legalcode
% Source code:   To be defined
% Reference  :   To be defined
% Date       :   July 2023
% -------------------------------------------------------------------------
% Description:   Import bony landmarks from FCSV files
% -------------------------------------------------------------------------
% Dependencies : - 3D Kinematics and Inverse Dynamics toolbox by Raphaël Dumas: https://fr.mathworks.com/matlabcentral/fileexchange/58021-3d-kinematics-and-inverse-dynamics?s_tid=prof_contriblnk
% -------------------------------------------------------------------------
% This work is licensed under the Creative Commons Attribution - 
% NonCommercial 4.0 International License. To view a copy of this license, 
% visit http://creativecommons.org/licenses/by-nc/4.0/ or send a letter to 
% Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
% -------------------------------------------------------------------------

function Bone = SetSegmentCoordinateSystems(Bone,type,itrial)

% -------------------------------------------------------------------------
% THORAX
% Wu et al. 2005
% -------------------------------------------------------------------------
if strcmp(type,'Static')
    Bone(4).(type)(itrial).SCS.O = Bone(4).(type)(itrial).Landmark(5).coordinates;
    Bone(4).(type)(itrial).SCS.Y = Vnorm_array3((Bone(4).(type)(itrial).Landmark(5).coordinates + ...
                                                 Bone(4).(type)(itrial).Landmark(11).coordinates)/2 - ...
                                                (Bone(4).(type)(itrial).Landmark(12).coordinates + ...
                                                 Bone(4).(type)(itrial).Landmark(14).coordinates)/2);
    Bone(4).(type)(itrial).SCS.Z = Vnorm_array3(cross(Bone(4).(type)(itrial).Landmark(5).coordinates - ...
                                                      (Bone(4).(type)(itrial).Landmark(12).coordinates + ...
                                                       Bone(4).(type)(itrial).Landmark(14).coordinates)/2, ...
                                                      Bone(4).(type)(itrial).Landmark(11).coordinates - ...
                                                      (Bone(4).(type)(itrial).Landmark(12).coordinates + ...
                                                       Bone(4).(type)(itrial).Landmark(14).coordinates)/2));
    Bone(4).(type)(itrial).SCS.X = Vnorm_array3(cross(Bone(4).(type)(itrial).SCS.Y,Bone(4).(type)(itrial).SCS.Z));
end
% Homogeneous matrix
Bone(4).(type)(itrial).SCS.T     = [Bone(4).(type)(itrial).SCS.X ...
                                    Bone(4).(type)(itrial).SCS.Y ...
                                    Bone(4).(type)(itrial).SCS.Z ...
                                    Bone(4).(type)(itrial).SCS.O; ...
                                    zeros(1,1,size(Bone(4).(type)(itrial).SCS.X,3)) ...
                                    zeros(1,1,size(Bone(4).(type)(itrial).SCS.X,3)) ...
                                    zeros(1,1,size(Bone(4).(type)(itrial).SCS.X,3)) ...
                                    ones(1,1,size(Bone(4).(type)(itrial).SCS.X,3))];
% Related Q parameters (Naaim thesis)
rP4                              = (Bone(4).(type)(itrial).Landmark(5).coordinates + ...
                                    Bone(4).(type)(itrial).Landmark(11).coordinates)/2;
rD4                              = (Bone(4).(type)(itrial).Landmark(12).coordinates + ...
                                    Bone(4).(type)(itrial).Landmark(14).coordinates)/2;
w4                               = Bone(4).(type)(itrial).SCS.Z;
u4                               = Vnorm_array3(cross((rP4-rD4),w4));
Bone(4).(type)(itrial).SCS.Q     = [u4; rP4; rD4; w4];
Bone(4).(type)(itrial).SCS.rM    = [Bone(4).(type)(itrial).Landmark(1) ...
                                    Bone(4).(type)(itrial).Landmark(2) ...
                                    Bone(4).(type)(itrial).Landmark(3) ...
                                    Bone(4).(type)(itrial).Landmark(4)]; % Cluster markers

% -------------------------------------------------------------------------
% HUMERUS
% Wu et al. 2005 (1st option)
% -------------------------------------------------------------------------
if strcmp(type,'Static')
    Bone(1).(type)(itrial).SCS.O = Bone(1).(type)(itrial).Landmark(12).coordinates;
    Bone(1).(type)(itrial).SCS.Y = Vnorm_array3(Bone(1).(type)(itrial).Landmark(12).coordinates - ...
                                                (Bone(1).(type)(itrial).Landmark(5).coordinates + ...
                                                Bone(1).(type)(itrial).Landmark(6).coordinates)/2);
    Bone(1).(type)(itrial).SCS.X = Vnorm_array3(cross((Bone(1).(type)(itrial).Landmark(5).coordinates - ...
                                                Bone(1).(type)(itrial).Landmark(12).coordinates),...
                                                (Bone(1).(type)(itrial).Landmark(6).coordinates - ...
                                                Bone(1).(type)(itrial).Landmark(12).coordinates)));
    Bone(1).(type)(itrial).SCS.Z = Vnorm_array3(cross(Bone(1).(type)(itrial).SCS.X,Bone(1).(type)(itrial).SCS.Y));
end
% Homogeneous matrix
Bone(1).(type)(itrial).SCS.T     = [Bone(1).(type)(itrial).SCS.X ...
                                    Bone(1).(type)(itrial).SCS.Y ...
                                    Bone(1).(type)(itrial).SCS.Z ...
                                    Bone(1).(type)(itrial).SCS.O; ...
                                    zeros(1,1,size(Bone(1).(type)(itrial).SCS.X,3)) ...
                                    zeros(1,1,size(Bone(1).(type)(itrial).SCS.X,3)) ...
                                    zeros(1,1,size(Bone(1).(type)(itrial).SCS.X,3)) ...
                                    ones(1,1,size(Bone(1).(type)(itrial).SCS.X,3))];
% Related Q parameters (Naaim thesis)
u1                               = Bone(1).(type)(itrial).SCS.X;
rP1                              = Bone(1).(type)(itrial).Landmark(12).coordinates;
rD1                              = (Bone(1).(type)(itrial).Landmark(5).coordinates + ...
                                   Bone(1).(type)(itrial).Landmark(6).coordinates)/2;
w1                               = Bone(1).(type)(itrial).SCS.Z;
Bone(1).(type)(itrial).SCS.Q     = [u1; rP1; rD1; w1];
Bone(1).(type)(itrial).SCS.rM    = [Bone(1).(type)(itrial).Landmark(1) ...
                                    Bone(1).(type)(itrial).Landmark(2) ...
                                    Bone(1).(type)(itrial).Landmark(3) ...
                                    Bone(1).(type)(itrial).Landmark(4)]; % Cluster markers

% -------------------------------------------------------------------------
% SCAPULA
% Wu et al. 2005
% -------------------------------------------------------------------------
if strcmp(type,'Static')
    Bone(2).(type)(itrial).SCS.O = Bone(2).(type)(itrial).Landmark(7).coordinates;
    Bone(2).(type)(itrial).SCS.Z = Vnorm_array3(Bone(2).(type)(itrial).Landmark(7).coordinates - ...
                                        Bone(2).(type)(itrial).Landmark(12).coordinates);
    Bone(2).(type)(itrial).SCS.X = Vnorm_array3(cross((Bone(2).(type)(itrial).Landmark(12).coordinates - ...
                                               Bone(2).(type)(itrial).Landmark(5).coordinates),...
                                              (Bone(2).(type)(itrial).Landmark(7).coordinates - ...
                                               Bone(2).(type)(itrial).Landmark(5).coordinates)));
    Bone(2).(type)(itrial).SCS.Y = Vnorm_array3(cross(Bone(2).(type)(itrial).SCS.Z,Bone(2).(type)(itrial).SCS.X));
end
% Homogeneous matrix
Bone(2).(type)(itrial).SCS.T     = [Bone(2).(type)(itrial).SCS.X ...
                                    Bone(2).(type)(itrial).SCS.Y ...
                                    Bone(2).(type)(itrial).SCS.Z ...
                                    Bone(2).(type)(itrial).SCS.O; ...
                                    zeros(1,1,size(Bone(2).(type)(itrial).SCS.X,3)) ...
                                    zeros(1,1,size(Bone(2).(type)(itrial).SCS.X,3)) ...
                                    zeros(1,1,size(Bone(2).(type)(itrial).SCS.X,3)) ...
                                    ones(1,1,size(Bone(2).(type)(itrial).SCS.X,3))];
% Related Q parameters (Naaim thesis)
u2                               = Bone(2).(type)(itrial).SCS.X;
rP2                              = Bone(2).(type)(itrial).Landmark(11).coordinates;
for t = 1:size(Bone(2).(type)(itrial).Landmark(1).coordinates,3)
    temp = [];
    for ipoint = 12+1:size(Bone(2).(type)(itrial).Landmark,2) % Points defining the glenoid contour
        temp = [temp Bone(2).(type)(itrial).Landmark(ipoint).coordinates(:,:,t)];
    end
    rD2(:,:,t) = sum(temp,2)/22; % Centre of the glenoid fossa
end
w2                               = Vnorm_array3(Bone(2).(type)(itrial).Landmark(7).coordinates - ...
                                                Bone(2).(type)(itrial).Landmark(12).coordinates);
Bone(2).(type)(itrial).SCS.Q     = [u2; rP2; rD2; w2];
Bone(2).(type)(itrial).SCS.rM    = [Bone(2).(type)(itrial).Landmark(1) ...
                                    Bone(2).(type)(itrial).Landmark(2) ...
                                    Bone(2).(type)(itrial).Landmark(3) ...
                                    Bone(2).(type)(itrial).Landmark(4)]; % Cluster markers

% -------------------------------------------------------------------------
% CLAVICLE
% Wu et al. 2005
% -------------------------------------------------------------------------
if contains(type,'Static')
    Bone(3).(type)(itrial).SCS.O  = Bone(3).(type)(itrial).Landmark(7).coordinates;
    Bone(3).(type)(itrial).SCS.Z  = Vnorm_array3(Bone(3).(type)(itrial).Landmark(9).coordinates - ...
                                                 Bone(3).(type)(itrial).Landmark(7).coordinates);
    Bone(3).(type)(itrial).SCS.X  = Vnorm_array3(cross(Bone(4).(type)(itrial).SCS.Y,Bone(3).(type)(itrial).SCS.Z));
    Bone(3).(type)(itrial).SCS.Y  = Vnorm_array3(cross(Bone(3).(type)(itrial).SCS.Z,Bone(3).(type)(itrial).SCS.X));
    % Homogeneous matrix
    Bone(3).(type)(itrial).SCS.T  = [Bone(3).(type)(itrial).SCS.X ...
                                     Bone(3).(type)(itrial).SCS.Y ...
                                     Bone(3).(type)(itrial).SCS.Z ...
                                     Bone(3).(type)(itrial).SCS.O; ...
                                     zeros(1,1,size(Bone(3).(type)(itrial).SCS.X,3)) ...
                                     zeros(1,1,size(Bone(3).(type)(itrial).SCS.X,3)) ...
                                     zeros(1,1,size(Bone(3).(type)(itrial).SCS.X,3)) ...
                                     ones(1,1,size(Bone(3).(type)(itrial).SCS.X,3))];
    % Related Q parameters (no reference)
    u3                            = Bone(3).(type)(itrial).SCS.X;
    rP3                           = Bone(3).(type)(itrial).Landmark(7).coordinates;
    rD3                           = Bone(3).(type)(itrial).Landmark(9).coordinates;
    w3                            = Bone(3).(type)(itrial).SCS.Z;
    Bone(3).(type)(itrial).SCS.Q  = [u3; rP3; rD3; w3];
    Bone(3).(type)(itrial).SCS.rM = [Bone(3).(type)(itrial).Landmark(1) ...
                                     Bone(3).(type)(itrial).Landmark(2) ...
                                     Bone(3).(type)(itrial).Landmark(3) ...
                                     Bone(3).(type)(itrial).Landmark(4)]; % Cluster markers  
elseif contains(type,'Trial')
    Bone(3).(type)(itrial).SCS.T  = [Bone(3).(type)(itrial).SCS.X ...
                                     Bone(3).(type)(itrial).SCS.Y ...
                                     Bone(3).(type)(itrial).SCS.Z ...
                                     Bone(3).(type)(itrial).SCS.O; ...
                                     zeros(1,1,size(Bone(3).(type)(itrial).SCS.X,3)) ...
                                     zeros(1,1,size(Bone(3).(type)(itrial).SCS.X,3)) ...
                                     zeros(1,1,size(Bone(3).(type)(itrial).SCS.X,3)) ...
                                     ones(1,1,size(Bone(3).(type)(itrial).SCS.X,3))];
    % Related Q parameters (no reference)
    u3                            = Bone(3).(type)(itrial).SCS.X;
    rP3                           = Bone(3).(type)(itrial).Landmark(7).coordinates;
    rD3                           = Bone(3).(type)(itrial).Landmark(9).coordinates;
    w3                            = Bone(3).(type)(itrial).SCS.Z;
    Bone(3).(type)(itrial).SCS.Q  = [u3; rP3; rD3; w3];
    Bone(3).(type)(itrial).SCS.rM = [Bone(3).(type)(itrial).Landmark(1) ...
                                     Bone(3).(type)(itrial).Landmark(2) ...
                                     Bone(3).(type)(itrial).Landmark(3) ...
                                     Bone(3).(type)(itrial).Landmark(4)]; % Cluster markers
end
clear rP3 rD3 w3 u3;